### ISSUE TITLE
Parsing of newline and whitespace characters

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-tools#16]
In production, the article XML files for eLife do not have newlines.  For readability, the kitchen sink XML does have newlines.

To run automated tests, these newlines are stripped from what the parser finds in the article.

Proposed is some change to how newlines are treated. I think since the new lines are not used in any system logic, we could change the parser itself to strip them out at the time of parsing.

**Comment by lsh-0** [comment]
The result being tested should not be munged to fit our tests. Our tests describe our expectations and then the code should figure out how to fill them.

My proposal is to treat the current parseJATS.py file as the source of 'raw' values extracted from the xml and create a new interface for our ideal values that have newlines and whitespace etc stripped.

See: https://github.com/elifesciences/elife-tools/issues/17

**Comment by gnott** [comment]
I see, if the newlines have value we will keep them in "raw" type requests.

**Comment by lsh-0** [comment]
its not that the newlines have value, we *do* want to strip them out, but our tests must reflect the reality of things: those functions are returning a value with newlines in them.

if we want a version of those values with newlines and whitespace stripped, we create a func  or a switch or some mechanism that does that and then we test our expectations against *that* - we don't alter the value for testing.

**Comment by gnott** [comment]
I really meant they would have value if, say, you wanted to be sure the file had no new line characters. Then you'd need to be able to test the raw data to look for the absence of new lines.

**Comment by gnott** [comment]
On closer inspection, the whitespace issues extend beyond the "extra" whitespace found in the kitchen sink XML. 

The liberal use of beautifulsoup's ``get_text(" ")`` to join parts together with a space character as the join character, along with later manipulation by a decorator to that whitespace, results in an unpredictable string as the end result.

Initially some tweaks to the whitespace is planned.

Next phase will be to more precisely extract individual tags from each part of the article XML so it can be reassembled more carefully into a final string.
