### ISSUE TITLE
separate the extraction of raw values from the cleaned/transformed values

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/elife-tools#17]
I would like a module that I can count on for returning 'ideal' values that depends upon a module that deals solely with extracting raw values.

For example: calling `parser.title(soup)` would give me the ideal version of the article title  (no new lines, no whitespace, etc)

calling `parser.raw_title(soup)` or perhaps `parser.title(soup, raw=True)` would give me the untransformed version straight from the xml.

Ian has suggested in the spirit of developer friendliness that we could also make the extracted xml node available ...

**Comment by gnott** [comment]
I am using something in the elementree parser elements (to come) with "raw", and I think we may have even more variants for different use cases.

I have an idea I'd like to try the ``title()`` being sent via a decorator through a string filterer, calling ``raw_title`` would not engage the filter.  If it works the extra code to be added would be minimal.

**Comment by lsh-0** [comment]
my proposal for a raw version and an 'ideal' version is that the extraction being done is likely to be copied and pasted into similar functions that need the same data but a different type of output - I'm thinking lists of authors or references here. 
The raw version would extract all of the authors and then there would be a `parser.authors` function that returns the first initial, middle intitial and last name of the first three and then 'et al' for the rest (just a crude example).

**Comment by gnott** [comment]
To clarify, would the raw values ever include nested XML tags?

It will need to support returning a title like ``Bacterial regulation of <italic>A. species</italic>`` when it supplies data to crossref and pubmed feeds.

**Comment by lsh-0** [comment]
I'm thinking we bypass raw strings with their embedded newlines and whatever and return the raw nodes BS/lxml return after extraction as per Ian's suggestion - that seems more useful. In that case the raw value *would* include child nodes.

**Comment by gnott** [comment]
I think I see now - more refactoring in the extraction of BS nodes to return nodes when possible. Then the "last mile" is transforming those into strings and lists of strings.

**Comment by lsh-0** [comment]
pretty much. I'll set up a new branch that introduces this approach and get a feel for how much work it will be.

**Comment by gnott** [comment]
I started a little yesterday on my working branch, and I noticed the whitespace issues. I'd like to continue that tweak to its completion. Then, I think we could write tests for what we really want to see, rather than just taking beautifulsoup's ``get_text()`` return value.

**Comment by lsh-0** [comment]
sure, I spent an hour on it today which I'll push up soon.

There are some huge chunks of code in there I don't want to touch and
they're giving me second thoughts, but a lot of the satellite code is small
and self contained. Testing against nodes returned by BS is a PITA.

On Tue, Mar 31, 2015 at 4:43 PM, Graham Nott <notifications@github.com>
wrote:

> I started a little yesterday on my working branch, and I noticed the
> whitespace issues. I'd like to continue that tweak to its completion. Then,
> I think we could write tests for what we really want to see, rather than
> just taking beautifulsoup's get_text() return value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/elife-tools/issues/17#issuecomment-88138162>
> .
>



-- 

Luke Skibinski

Human being that
writes software,
manages systems.

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by lsh-0** [comment]
ok - putting my money where my mouth is:

https://github.com/elifesciences/elife-tools/commit/761b48fb673af36e77b438c2eb1c46ad5f2ed196

Some major surgery happened and I can still see room for improvement, but the code and commit message say it all. Would love some feedback.

**Comment by gnott** [comment]
I like it, please pull request into master, and I'll work from this revision.

**Comment by lsh-0** [comment]
https://github.com/elifesciences/elife-tools/pull/20
