### ISSUE TITLE
provide a method to return the digest

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/elife-tools#18]

**Comment by gnott** [comment]
The simple abstract tends to be one paragraph, but the digest / executive summary has multiple paragraphs.

Do you know if this should be returned as

* one block of text
* a list with one item per paragraph
* a block of text with ``<p>`` tags included
* and/or all inline tagging (``<italic>``, ``<sup>``, etc.)
* or all the above

I think there will be a few variants, and I can get started on some basic parsing for now.

**Comment by lsh-0** [comment]
- a block of text with <p> tags included
   - and/or all inline tagging (<italic>, <sup>, etc.)

I would suggest the variants containing xml would belong in the rawJATS.py
and the parseJATS.py would contain plain text with new lines.


On Thu, Apr 9, 2015 at 9:51 PM, Graham Nott <notifications@github.com>
wrote:

> The simple abstract tends to be one paragraph, but the digest / executive
> summary has multiple paragraphs.
>
> Do you know if this should be returned as
>
>    - one block of text
>    - a list with one item per paragraph
>    - a block of text with <p> tags included
>    - and/or all inline tagging (<italic>, <sup>, etc.)
>    - or all the above
>
> I think there will be a few variants, and I can get started on some basic
> parsing for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elifesciences/elife-tools/issues/18#issuecomment-91353179>
> .
>



-- 

Luke Skibinski

Human being that
writes software,
manages systems.

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by gnott** [comment]
Parsing the digest has good support now.
