### ISSUE TITLE
strange bit of code

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/elife-tools#25]
Any idea what is going on here?
https://github.com/elifesciences/elife-tools/blob/master/elifetools/parseJATS.py#L648

Is BeautifulSoup doing something strange so that doing the same thing again may return a result, or can we get rid of lines 647+648?

**Comment by gnott** [comment]
It looks like leftovers of a quick conversion to JATS format. The original function supported ppub and epub types, which we no longer use

https://github.com/elifesciences/elife-api-prototype/blob/master/parseNLM.py#L857

Seeing as we only expect "pub" the repeated line can be removed.

**Comment by gnott** [comment]
Fixed in https://github.com/elifesciences/elife-tools/pull/27
