### ISSUE TITLE
Update all DOI links to https://doi.org?

### ISSUE THREAD

**Issue by katrinleinweber** [elifesciences/elife-tools#273]
Dear eLifeSciences team,

I noticed 321e724929bd597a878fe0e703c2410ef50f7ee5 and 

https://github.com/elifesciences/elife-tools/blob/b22ca98da20b03e47ecf05b7a77194fa0aa62ba5/elifetools/sample-xml/elife-00666.xml#L34

so I was wondering whether you are planning to update the many DOI links in your repos? Do I understand correctly, that for example all the test data in here is still based on the old `http://dx…` resolver. Intentional?

Also, is https://github.com/elifesciences/elife-ingest-xsl archived because it is no longer used, or because you don't plan on changing it while it remains in use?

Thanks for infos about this :-)

**Comment by giorgiosironi** [comment]
I can answer about `elife-ingest-xsl`. This library was used in the 2016-era `elifesciences.org`, which has now been retired since the launch of the new website in 2017. We have archived the repository as it will never be changed nor used again in eLife.

**Comment by gnott** [comment]
Going forward, using ``https://doi.org`` links for DOI URLs is preferred. There are still many older articles with older ``http://dox.org.org`` links and those will not be changed. The parser in this library supports either type.

In the current JSON format of article data, the link prefix is stripped from DOI values (using the ``utils.py`` function ``doi_uri_to_doi()``, https://github.com/elifesciences/elife-tools/blob/develop/elifetools/utils.py#L186). Then, when displayed on web pages the ``https://doi.org/`` prefix is added back in the front-end logic as required.

**Comment by katrinleinweber** [comment]
Cool, thanks for explaining :-)
