### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-tools#315]
This library is currently supported in Python 2.7 and Python 3, tested in both `2.7` and `3.5` in automated tests. Considering the EOF date of Python 2, there are a couple things we can do before the end of 2019 here, including:

- [x] remove testing for Python 2.7 in test scripts
- [x] remove Python 2.7 from supported versions in the `setup.py`
- [x] try removing `six` or other Python 2 code hooks if it is straightforward
- [x] refactor any conditional logic that is different depending on the Python version, for example calling `unicode()`, and things related to strings and character encoding
- [x] I think can also drop any imports from `__future__` in this library

I'm not sure if there's any advantage to keep the testing and stated support beyond December 31, 2019. Is there a reason to have some overlap for version support? Any comments @lsh-0, @giorgiosironi, @de-code?

**Comment by lsh-0** [comment]
projects that depend on elife-tools:
- [x] https://github.com/elifesciences/bot-lax-adaptor
- [ ] https://github.com/elifesciences/jats-generator
- [ ] https://github.com/elifesciences/ejp-csv-parser
- [ ] https://github.com/elifesciences/elife-pubmed-xml-generation
- [ ] https://github.com/elifesciences/elife-crossref-xml-generation
- [ ] https://github.com/elifesciences/digest-parser
- [ ] https://github.com/elifesciences/elife-article
- [ ] https://github.com/elifesciences/elife-crossref-flask
- [x] https://github.com/elifesciences/elife-bot

I'll go through them and check those that are support python3

**Comment by giorgiosironi** [comment]
I agree that the main issue is projects that use this library and should be ported to Python 3. As soon as that happens, would drop Python 2 and enjoy the simplicity of one Python major version.

**Comment by lsh-0** [comment]
>  simplicity of one Python major version

you mean, three, right? 3.4, 3.5, 3.6 with a mix of apps using containers, 16.04 and 18.04.

personally I would err on the language feature introduced in 3.4 so it's forwards compatible with everything, but python feels more like perl and php to me these days. Let the devs do what they want, we'll accommodate them somehow.

**Comment by giorgiosironi** [comment]
One major version, three minor versions; at least you don't need `six` anymore.

**Comment by giorgiosironi** [comment]
> I would err on the language feature set introduced in 3.4

A miminum Python version is welcome. Seems [3.4 is EOL already](https://devguide.python.org/devcycle/#end-of-life-branches) so should that be 3.5? 3.4 was what we had on 14.04 IIRC, which has now been removed?

/cc @GiancarloFusiello on suggestions for a minimum Python 3.x version.

**Comment by GiancarloFusiello** [comment]
I would use the latest version of python that the project dependencies support. Python 3.7 latest version is 3.7.4. Lots of new features, optimisations and bug/security fixes https://docs.python.org/3/whatsnew/3.7.html

**Comment by lsh-0** [comment]
> One major version, three minor versions

Python doesn't use semantic versioning. 

> I would use the latest version of python that the project dependencies support. 

I'm being pedantic, but I would caveat that - you need to understand the operating environment of the application.

**Comment by gnott** [comment]
Good point to ensure all the dependent libraries are also compatible. `elife-article` I'm sure that it is compatible but it isn't stated as so. I'm updating that now. We might want a consistent test and stated python version support for each of these identified libraries.

**Comment by lsh-0** [comment]
> We might want a consistent test and stated python version support for each of these identified libraries.

actually, your work with the environments in `tox.ini` and `setup.py` categories is what let me tick those other libraries off so quickly, so we're already 99% of the way there. It's just that one outstanding project that doesn't look like it's been updated yet.

**Comment by gnott** [comment]
Interesting example on https://pypi.org/project/pytest/ it shows as `Python :: 3 :: Only`. I'm not planning to add that classifier to the `setup.py` here, but it might be a good thing to display, causing less confusion after `py27` support is dropped.

**Comment by gnott** [comment]
PR is merged, I think this ticket is completed now so closing!

**Comment by lsh-0** [comment]
thanks, @gnott
