### ISSUE TITLE
pip fails to install

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/elife-tools#47]
I get the following error. 

#include "libxml/xmlversion.h"

             ^

    1 error generated.

    error: command 'clang' failed with exit status 1

    ----------------------------------------
    Command "/Users/ian/.virtualenvs/elife-tools/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/fc/_q9f5y4n51bb7kjf_tv7l9xw0000gn/T/pip-build-jNqjKo/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/fc/_q9f5y4n51bb7kjf_tv7l9xw0000gn/T/pip-YsuDiW-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ian/.virtualenvs/elife-tools/bin/../include/site/python2.7" failed with error code 1 in /private/var/folders/fc/_q9f5y4n51bb7kjf_tv7l9xw0000gn/T/pip-build-jNqjKo/lxml

**Comment by lsh-0** [comment]
Fixed here: https://github.com/elifesciences/elife-tools/commit/942cff19abb9d7869a69a20cd7ec7417ae9401e8

Also, this belongs in Jira.
