### ISSUE TITLE
Speed up lettuce tests with caching

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-tools#7]
Tried a quick method of caching beautifulsoup parsed XML files so they are not parsed on each lettuce scenario step. It didn't speed up.

Another test, for example, would be to cache the authors and other data elements. This should make it faster to build the author list just once per file (the files do not change during the running of all the tests) and comparisons can be made with the cached data.

This may or may not speed things up significantly.

**Comment by lsh-0** [comment]
Are the tests slow enough to matter? Is caching even necessary?

**Comment by gnott** [comment]
These can be slow when building tests - I have a workaround now, just comment out tests not being worked on.

**Comment by lsh-0** [comment]
I wonder how fast the equivalent expressions in xslt/xpath/xquery would be
- or is it the building of the tests rather than the beautiful soup that is
slow?

**Comment by gnott** [comment]
Getting author data currently does lots of comparisons and follwing of xref tags to aff tags, etc. and I think the tests do this for every row in a scenario. The speed is not an issue right now, but this is just an idea to speed it up if we need to in the future.

**Comment by gnott** [comment]
Lettuce test are gone now.

**Comment by lsh-0** [comment]
wooo
